### ISSUE TITLE
add topics

### ISSUE THREAD

**Issue by Beliavsky** [FraJoMen/GA-cal#1]
I suggest adding the topics `genetic-algorithm`, `genetic-algorithms`, `numerical-optimization` in the About section at https://github.com/FraJoMen/GA-cal.

**Comment by FraJoMen** [comment]
Thanks a lot for the advice, but I can't find the About section. How should i do ?

**Comment by Beliavsky** [comment]
It's where you wrote, "Fortran software for automatically calibrating constitutive laws using Genetic Algorithms optimization.". Please see https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics for how to add topics.
